-- 1. Technologies Table
CREATE TABLE technologies (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    quadrant TEXT NOT NULL CHECK (quadrant IN ('Techniques', 'Tools', 'Platforms', 'Languages & Frameworks')),
    ring TEXT NOT NULL CHECK (ring IN ('Adopt', 'Trial', 'Assess', 'Hold')),
    tags TEXT[],
    source_url TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_updated TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Technology History Table
CREATE TABLE technology_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technology_id UUID REFERENCES technologies(id) ON DELETE CASCADE,
    change_description TEXT NOT NULL,
    changed_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    changed_by TEXT -- Could be user ID or email
);

-- 3. Enable Row Level Security
ALTER TABLE technologies ENABLE ROW LEVEL SECURITY;
ALTER TABLE technology_history ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies for technologies table
CREATE POLICY "Allow public read access on technologies" ON technologies FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to insert into technologies" ON technologies FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated users to update technologies" ON technologies FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated users to delete from technologies" ON technologies FOR DELETE TO authenticated USING (true);

-- 5. Create Policies for technology_history table
CREATE POLICY "Allow public read access on technology_history" ON technology_history FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to insert into technology_history" ON technology_history FOR INSERT TO authenticated WITH CHECK (true);
